/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package condicionescompetencias;

import javax.swing.JOptionPane;

/**
 *
 * @author david
 */
public class CondicionesCompetencias extends javax.swing.JFrame {

    /**
     * Creates new form CondicionesCompetencias
     */
    public CondicionesCompetencias() {
        initComponents();
        rc= new RCompartido();
        h1 = new Hilo(area1,rc,nAlgoritmo);
        h1.setName("DOG 1");
        h2 = new Hilo(area2,rc,nAlgoritmo);
        h2.setName("DOG 2");
        h3 = new Hilo(area3,rc,nAlgoritmo);
        h3.setName("DOG 3");
        h4 = new Hilo(area4,rc,nAlgoritmo);
        h4.setName("DOG 4");
    }
    
    public int getAlgoritmo(){
        int num=0;
        if(nAlgoritmo.getText().equals("Condiciones de Competencia")){
            num=0;
        }
        if(nAlgoritmo.getText().equals("Desactivacion de Interrupciones")){
            num=1;
        }
        if(nAlgoritmo.getText().equals("Peterson(VCerradura)")){
            num=2;
        }
        if(nAlgoritmo.getText().equals("Dekker(Alternancia Estricta)")){
            num=3;
        }
        if(nAlgoritmo.getText().equals("Dijkstra")){
            num=4;
        }
        if(nAlgoritmo.getText().equals("Mutex")){
            num=5;
        }
        if(nAlgoritmo.getText().equals("Mutex(API)")){
            num=6;
        }
        return num;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        bCorrer = new javax.swing.JButton();
        jTerminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        area1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        area2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        area3 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        area4 = new javax.swing.JTextArea();
        bKill = new javax.swing.JButton();
        nAlgoritmo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem_CC = new javax.swing.JMenuItem();
        jMenuItem_DI = new javax.swing.JMenuItem();
        jMenuItem_VC = new javax.swing.JMenuItem();
        jMenuItem_AE = new javax.swing.JMenuItem();
        jMenuItem_Dijkstra = new javax.swing.JMenuItem();
        jMenuItem_Mutex = new javax.swing.JMenuItem();
        jMenuItem_MutexAPI = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        bCorrer.setText("Correr");
        bCorrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCorrerActionPerformed(evt);
            }
        });

        jTerminar.setText("Terminar");
        jTerminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTerminarActionPerformed(evt);
            }
        });

        area1.setEditable(false);
        area1.setColumns(20);
        area1.setRows(5);
        area1.setMaximumSize(new java.awt.Dimension(150, 100));
        area1.setPreferredSize(new java.awt.Dimension(150, 100));
        jScrollPane1.setViewportView(area1);

        area2.setEditable(false);
        area2.setColumns(20);
        area2.setRows(5);
        area2.setPreferredSize(new java.awt.Dimension(150, 100));
        jScrollPane2.setViewportView(area2);

        area3.setEditable(false);
        area3.setColumns(20);
        area3.setRows(5);
        area3.setPreferredSize(new java.awt.Dimension(150, 100));
        jScrollPane3.setViewportView(area3);

        area4.setEditable(false);
        area4.setColumns(20);
        area4.setRows(5);
        area4.setPreferredSize(new java.awt.Dimension(150, 100));
        jScrollPane4.setViewportView(area4);

        bKill.setText("KILL");
        bKill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKillActionPerformed(evt);
            }
        });

        nAlgoritmo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nAlgoritmo.setText("Condiciones de Competencia");

        jMenu1.setText("File");

        jMenuItem7.setText("Cerrar");
        jMenu1.add(jMenuItem7);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("Algoritmos");

        jMenuItem_CC.setText("Condiciones de Competencia");
        jMenuItem_CC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_CCActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem_CC);

        jMenuItem_DI.setText("Desactivacion de Interrupciones");
        jMenuItem_DI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_DIActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem_DI);

        jMenuItem_VC.setText("Peterson(VCerradura)");
        jMenuItem_VC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_VCActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem_VC);

        jMenuItem_AE.setText("Dekker(Alternancia Estricta)");
        jMenuItem_AE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_AEActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem_AE);

        jMenuItem_Dijkstra.setText("Dijkstra");
        jMenuItem_Dijkstra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_DijkstraActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem_Dijkstra);

        jMenuItem_Mutex.setText("Mutex");
        jMenuItem_Mutex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_MutexActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem_Mutex);

        jMenuItem_MutexAPI.setText("Mutex(API)");
        jMenuItem_MutexAPI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_MutexAPIActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem_MutexAPI);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nAlgoritmo, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTerminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bCorrer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bKill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nAlgoritmo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(bCorrer)
                        .addGap(30, 30, 30)
                        .addComponent(jTerminar)
                        .addGap(30, 30, 30)
                        .addComponent(bKill))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane2)
                                .addComponent(jScrollPane3)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        nAlgoritmo.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCorrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCorrerActionPerformed
        h1.stop();
        h2.stop();
        h3.stop();
        h4.stop();
        
        rc= new RCompartido();
        h1 = new Hilo(area1,rc,nAlgoritmo);
        h1.setName("DOG 1");
        h2 = new Hilo(area2,rc,nAlgoritmo);
        h2.setName("DOG 2");
        h3 = new Hilo(area3,rc,nAlgoritmo);
        h3.setName("DOG 3");
        h4 = new Hilo(area4,rc,nAlgoritmo);
        h4.setName("DOG 4");
        
        area1.setText("");
        area2.setText("");
        area3.setText("");
        area4.setText("");
        
        h1.start();
        h2.start();
        h3.start();
        h4.start();
        
        bCorrer.setEnabled(false);
    }//GEN-LAST:event_bCorrerActionPerformed

    private void jTerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTerminarActionPerformed
        h1.stop();
        h2.stop();
        h3.stop();
        h4.stop();
        bCorrer.setEnabled(true);
    }//GEN-LAST:event_jTerminarActionPerformed

    private void bKillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKillActionPerformed
        int RKO = (int)(Math.random()*3);
         
        switch(RKO){
            case 0:
                try{
                    h1.setdead(true);
                }catch(Exception e){JOptionPane.showMessageDialog(null, "Error");}
                break;
            case 1:
                try{
                    h2.setdead(true);
                }catch(Exception e){JOptionPane.showMessageDialog(null, "Error");}
                break;
            case 2:
                try{
                    h3.setdead(true);
                }catch(Exception e){JOptionPane.showMessageDialog(null, "Error");}
                break;
            case 3:
                try{
                    h4.setdead(true);
                }catch(Exception e){JOptionPane.showMessageDialog(null, "Error");}
                break;
            default:
        }
    }//GEN-LAST:event_bKillActionPerformed

    private void jMenuItem_VCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_VCActionPerformed
        nAlgoritmo.setText(jMenuItem_VC.getText());
        bCorrer.setEnabled(true);
    }//GEN-LAST:event_jMenuItem_VCActionPerformed

    private void jMenuItem_MutexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_MutexActionPerformed
        nAlgoritmo.setText(jMenuItem_Mutex.getText());
        bCorrer.setEnabled(true);
    }//GEN-LAST:event_jMenuItem_MutexActionPerformed

    private void jMenuItem_DIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_DIActionPerformed
        nAlgoritmo.setText(jMenuItem_DI.getText());
        bCorrer.setEnabled(true);
    }//GEN-LAST:event_jMenuItem_DIActionPerformed

    private void jMenuItem_CCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_CCActionPerformed
        nAlgoritmo.setText(jMenuItem_CC.getText());
        bCorrer.setEnabled(true);
    }//GEN-LAST:event_jMenuItem_CCActionPerformed

    private void jMenuItem_DijkstraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_DijkstraActionPerformed
        
    }//GEN-LAST:event_jMenuItem_DijkstraActionPerformed

    private void jMenuItem_AEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_AEActionPerformed
        nAlgoritmo.setText(jMenuItem_AE.getText());
        bCorrer.setEnabled(true);
    }//GEN-LAST:event_jMenuItem_AEActionPerformed

    private void jMenuItem_MutexAPIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_MutexAPIActionPerformed
        nAlgoritmo.setText(jMenuItem_MutexAPI.getText());
        bCorrer.setEnabled(true);
    }//GEN-LAST:event_jMenuItem_MutexAPIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CondicionesCompetencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CondicionesCompetencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CondicionesCompetencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CondicionesCompetencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CondicionesCompetencias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area1;
    private javax.swing.JTextArea area2;
    private javax.swing.JTextArea area3;
    private javax.swing.JTextArea area4;
    private javax.swing.JButton bCorrer;
    private javax.swing.JButton bKill;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem_AE;
    private javax.swing.JMenuItem jMenuItem_CC;
    private javax.swing.JMenuItem jMenuItem_DI;
    private javax.swing.JMenuItem jMenuItem_Dijkstra;
    private javax.swing.JMenuItem jMenuItem_Mutex;
    private javax.swing.JMenuItem jMenuItem_MutexAPI;
    private javax.swing.JMenuItem jMenuItem_VC;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton jTerminar;
    public static javax.swing.JLabel nAlgoritmo;
    // End of variables declaration//GEN-END:variables
    private Hilo h1,h2,h3,h4;
    private RCompartido rc;
}
